# mkdocs serve

site_name: Frequently Asked Questions

site_url: https://ibm-mas-manage.github.io/faq/

repo_name: GitHub
repo_url: https://github.com/ibm-mas-manage/faq
edit_uri: blob/master/docs/

nav:
  - 'Frequently Asked Questions': index.md

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
  prev_next_buttons_location: none
extra_css:
  - extra.css
markdown_extensions:
  - toc:
      permalink: 
  - admonition
  # Add this to support expandable sections
  #- pymdownx.details

